In [12]:
import numpy as np
import pandas as pd

In [13]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [14]:
df = pd.read_csv("covid_toy.csv")
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['has_covid']), df['has_covid'], test_size=0.2)

In [16]:
X_train.head()

    age  gender  fever   cough       city
18   64  Female   98.0    Mild  Bangalore
17   40  Female   98.0  Strong      Delhi
82   24    Male   98.0    Mild    Kolkata
61   81  Female   98.0  Strong     Mumbai
77    8  Female  101.0    Mild    Kolkata

##  ------  Aam Zindagi  --------

### Adding simple imputer to add values in replace of missing values

In [19]:
# Adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])

X_train_fever.shape

(80, 1)

### Appyling Ordinal Encoding to Cough

In [23]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild', 'Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

### Appyling One Hot Encoding to -> gender , city

In [29]:
# OneHotEncoding -> gender, city
ohe = OneHotEncoder(drop='first', sparse_output=True)
X_train_gender_city = ohe.fit_transform(X_train[['gender', 'city']])

# also to test data
X_test_gender_city = ohe.fit_transform(X_test[['gender', 'city']])

X_train_gender_city.shape

(80, 4)

## Extracting age

In [45]:
# extract the age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also to the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [36]:
# concatinate the columns
X_train_transformed = np.concatenate((X_train_age, X_train_fever, X_train_gender_city.toarray(), X_train_cough), axis=1)
# also to the test data
X_test_transformed = np.concatenate((X_test_age, X_test_fever, X_test_gender_city.toarray(), X_test_cough), axis=1)

X_train_transformed.shape

(80, 7)

## ------- Mintos Zindagi ---------

In [38]:
from sklearn.compose import ColumnTransformer

In [41]:
transformer = ColumnTransformer(transformers=[
    ('tnf1', SimpleImputer(),['fever']),
    ('tnf2', OrdinalEncoder(categories=[['Mild', 'Strong']]),['cough']),
    ('tnf3', OneHotEncoder(drop='first', sparse_output=True), ['gender', 'city'])
], remainder='passthrough')

In [43]:
transformer.fit_transform(X_train).shape

(80, 7)

In [44]:
transformer.transform(X_test).shape

(20, 7)