In [1]:
import numpy as np
import pandas as pd

In [2]:
date = pd.read_csv("orders.csv")
time = pd.read_csv("messages.csv")

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

## Working with Date

In [7]:
# Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

## Extract Year

In [10]:
date['date_year'] = date['date'].dt.year
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

## Extract Month

In [12]:
date['date_month_no'] = date['date'].dt.month
date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

In [14]:
# If you want name of the month
date['date_month_no'] = date['date'].dt.month_name()
date.head()

        date  product_id  city_id  orders  date_year date_month_no
0 2019-12-10        5628       25       3       2019      December
1 2018-08-15        3646       14     157       2018        August
2 2018-10-23        1859       25       1       2018       October
3 2019-08-17        7292       25       1       2019        August
4 2019-01-06        4344       25       3       2019       January

## Extract Days

In [15]:
date['date_day'] = date['date'].dt.day
date.head()

        date  product_id  city_id  orders  date_year date_month_no  date_day
0 2019-12-10        5628       25       3       2019      December        10
1 2018-08-15        3646       14     157       2018        August        15
2 2018-10-23        1859       25       1       2018       October        23
3 2019-08-17        7292       25       1       2019        August        17
4 2019-01-06        4344       25       3       2019       January         6

In [18]:
# if you want day name of the month
date['date_day'] = date['date'].dt.day_name()
date.head()

        date  product_id  city_id  orders  date_year date_month_no   date_day
0 2019-12-10        5628       25       3       2019      December    Tuesday
1 2018-08-15        3646       14     157       2018        August  Wednesday
2 2018-10-23        1859       25       1       2018       October    Tuesday
3 2019-08-17        7292       25       1       2019        August   Saturday
4 2019-01-06        4344       25       3       2019       January     Sunday

### Day of the week

In [22]:
date['day_now'] = date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_day,day_now
0,2019-12-10,5628,25,3,2019,December,Tuesday,1
1,2018-08-15,3646,14,157,2018,August,Wednesday,2
2,2018-10-23,1859,25,1,2018,October,Tuesday,1
3,2019-08-17,7292,25,1,2019,August,Saturday,5
4,2019-01-06,4344,25,3,2019,January,Sunday,6

In [23]:
date['day_now_name'] = date['date'].dt.day_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_day,day_now,day_now_name
0,2019-12-10,5628,25,3,2019,December,Tuesday,1,Tuesday
1,2018-08-15,3646,14,157,2018,August,Wednesday,2,Wednesday
2,2018-10-23,1859,25,1,2018,October,Tuesday,1,Tuesday
3,2019-08-17,7292,25,1,2019,August,Saturday,5,Saturday
4,2019-01-06,4344,25,3,2019,January,Sunday,6,Sunday

## Checking is weekend?

In [25]:
date['date_is_weekend'] = np.where(date['day_now_name'].isin(['Saturday', 'Sunday']), 1,0)
date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month_no,date_day,day_now,day_now_name,date_is_weekend
0,2019-12-10,2019,December,Tuesday,1,Tuesday,0
1,2018-08-15,2018,August,Wednesday,2,Wednesday,0
2,2018-10-23,2018,October,Tuesday,1,Tuesday,0
3,2019-08-17,2019,August,Saturday,5,Saturday,1
4,2019-01-06,2019,January,Sunday,6,Sunday,1

## Extract week of the year

In [29]:
date['date_week'] = date['date'].dt.isocalendar().week
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_day,day_now,day_now_name,date_is_weekend,date_week
0,2019-12-10,5628,25,3,2019,December,Tuesday,1,Tuesday,0,50
1,2018-08-15,3646,14,157,2018,August,Wednesday,2,Wednesday,0,33
2,2018-10-23,1859,25,1,2018,October,Tuesday,1,Tuesday,0,43
3,2019-08-17,7292,25,1,2019,August,Saturday,5,Saturday,1,33
4,2019-01-06,4344,25,3,2019,January,Sunday,6,Sunday,1,1

### Extract Quater

In [35]:
date['quater'] = date['date'].dt.quarter
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_day,day_now,day_now_name,date_is_weekend,date_week,quater
0,2019-12-10,5628,25,3,2019,December,Tuesday,1,Tuesday,0,50,4
1,2018-08-15,3646,14,157,2018,August,Wednesday,2,Wednesday,0,33,3
2,2018-10-23,1859,25,1,2018,October,Tuesday,1,Tuesday,0,43,4
3,2019-08-17,7292,25,1,2019,August,Saturday,5,Saturday,1,33,3
4,2019-01-06,4344,25,3,2019,January,Sunday,6,Sunday,1,1,1

## Extract Semester

In [37]:
date['semester'] = np.where(date['quater'].isin([1,2]), 1, 2)
date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month_no,date_day,day_now,day_now_name,date_is_weekend,date_week,quater,semester
0,2019-12-10,2019,December,Tuesday,1,Tuesday,0,50,4,2
1,2018-08-15,2018,August,Wednesday,2,Wednesday,0,33,3,2
2,2018-10-23,2018,October,Tuesday,1,Tuesday,0,43,4,2
3,2019-08-17,2019,August,Saturday,5,Saturday,1,33,3,2
4,2019-01-06,2019,January,Sunday,6,Sunday,1,1,1,1

## Extract Time elapsed between dates

In [38]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 6, 23, 4, 41, 41, 818144)

In [39]:
today - date['date']

0     2387 days 04:41:41.818144
1     2869 days 04:41:41.818144
2     2800 days 04:41:41.818144
3     2502 days 04:41:41.818144
4     2725 days 04:41:41.818144
                 ...
995   2815 days 04:41:41.818144
996   2756 days 04:41:41.818144
997   2604 days 04:41:41.818144
998   2669 days 04:41:41.818144
999   2443 days 04:41:41.818144
Name: date, Length: 1000, dtype: timedelta64[ns]

In [41]:
# if only want days
(today - date['date']).dt.days

0      2387
1      2869
2      2800
3      2502
4      2725
       ...
995    2815
996    2756
997    2604
998    2669
999    2443
Name: date, Length: 1000, dtype: int64

In [44]:
# month passed
np.round((today - date['date']).dt.days /30.41, 0)

0      78.0
1      94.0
2      92.0
3      82.0
4      90.0
       ...
995    93.0
996    91.0
997    86.0
998    88.0
999    80.0
Name: date, Length: 1000, dtype: float64

## Working Time

In [45]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [47]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [52]:
time['date'] = pd.to_datetime(time['date'])

In [53]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
 2   hour    1000 non-null   int32
 3   min     1000 non-null   int32
 4   sec     1000 non-null   int32
dtypes: datetime64[ns](1), int32(3), object(1)
memory usage: 27.5+ KB

### Extract hour, minutes, seconds

In [60]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

## Extract Time part

In [61]:
time['time'] = time['date'].dt.time
time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

## Time difference

In [62]:
today - time['date']

0     4573 days 03:51:41.818144
1     4437 days 05:01:41.818144
2     4923 days 04:20:41.818144
3     4225 days 04:10:41.818144
4     4622 days 05:30:41.818144
                 ...
995   5212 days 03:51:41.818144
996   4533 days 05:27:41.818144
997   4998 days 05:04:41.818144
998   5114 days 05:07:41.818144
999   4386 days 05:16:41.818144
Name: date, Length: 1000, dtype: timedelta64[ns]

In [63]:
# in seconds
(today - time['date']) / np.timedelta64(1,'s')

0      3.951211e+08
1      3.833749e+08
2      4.253628e+08
3      3.650550e+08
4      3.993606e+08
           ...
995    4.503307e+08
996    3.916709e+08
997    4.318455e+08
998    4.418681e+08
999    3.789694e+08
Name: date, Length: 1000, dtype: float64

In [64]:
# in minutes
(today - time['date']) / np.timedelta64(1,'m')

0      6.585352e+06
1      6.389582e+06
2      7.089381e+06
3      6.084251e+06
4      6.656011e+06
           ...
995    7.505512e+06
996    6.527848e+06
997    7.197425e+06
998    7.364468e+06
999    6.316157e+06
Name: date, Length: 1000, dtype: float64

In [65]:
# in hours
(today - time['date']) / np.timedelta64(1,'h')

0      109755.861616
1      106493.028283
2      118156.344949
3      101404.178283
4      110933.511616
           ...
995    125091.861616
996    108797.461616
997    119957.078283
998    122741.128283
999    105269.278283
Name: date, Length: 1000, dtype: float64